import type { Metadata } from "next";
import { Inter, Chonburi } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const chon = Chonburi({subsets: ["latin"], weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chon.className}>{children}</body>
    </html>
  );
}
